---
apiVersion: v1
data:
  config.json: |
    {
        "default_server_config": {
            "m.homeserver": {
                "base_url": "https://matrix.example.com",
                "server_name": "example.com"
            },
            "m.identity_server": {
                "base_url": "https://matrix.example.com"
            }
        },
        "disable_identity_server": false,
        "disable_custom_urls": false,
        "disable_guests": true,
        "disable_login_language_selector": false,
        "disable_3pid_login": false,
        "brand": "Riot",
        "integrations_ui_url": "https://scalar.vector.im/",
        "integrations_rest_url": "https://scalar.vector.im/api",
        "integrations_jitsi_widget_url": "https://scalar.vector.im/api/widgets/jitsi.html",
        "bug_report_endpoint_url": "https://riot.im/bugreports/submit",
        "defaultCountryCode": "GB",
        "showLabsSettings": true,
        "features": {
            "feature_pinning": "labs",
            "feature_custom_status": "labs",
            "feature_custom_tags": "labs",
            "feature_state_counters": "labs",
            "feature_many_integration_managers": "labs",
            "feature_mjolnir": "labs",
            "feature_dm_verification": "labs",
            "feature_cross_signing": "labs"
        },
        "default_federate": true,
        "welcomePageUrl": "home.html",
        "default_theme": "light",
        "roomDirectory": {
            "servers": [
                "example.com",
                "matrix.org"
            ]
        },
        "piwik": {
            "url": "https://piwik.riot.im/",
            "whitelistedHSUrls": ["https://matrix.org"],
            "whitelistedISUrls": ["https://vector.im", "https://matrix.org"],
            "siteId": 1
        },
        "enable_presence_by_hs_url": {
            "https://matrix.org": false
        }
    }
kind: ConfigMap
metadata:
  labels:
    app: riot
  name: riot-config
  namespace: matrix
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: riot
  name: riot
  namespace: matrix
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: riot
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: riot
  name: riot
  namespace: matrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: riot
  template:
    metadata:
      labels:
        app: riot
    spec:
      containers:
      - image: vectorim/riot-web:v1.5.6
        imagePullPolicy: IfNotPresent
        name: riot-web
        readinessProbe:
          tcpSocket:
            port: 80
        volumeMounts:
        - mountPath: /app/config.json
          name: riot-config
          subPath: config.json
      restartPolicy: Always
      volumes:
      - configMap:
          name: riot-config
        name: riot-config
